update Review.ReviewStatus set ReviewStatusDescription ='Stage 1 - Employee - Goals Not Started' where ReviewStatusCode='NOT_STARTED'
update Review.ReviewStatus set ReviewStatusDescription ='Stage 1 - Employee - Goals setting in progress' where ReviewStatusCode='GOALS_SETTING_IN_PROGRESS'
update Review.ReviewStatus set ReviewStatusDescription ='Stage 2 - Manager - Need to approve goals' where ReviewStatusCode='GOALS_SUBMITTED'
update Review.ReviewStatus set ReviewStatusDescription ='Stage 2 - Employee - Need more information' where ReviewStatusCode='NEED_TO_EDIT_GOALS'
update Review.ReviewStatus set ReviewStatusDescription ='Stage 3 - Employee - Goals Approved' where ReviewStatusCode='GOALS_FINALIZED'
update Review.ReviewStatus set ReviewStatusDescription ='Stage 4 - Employee - Goals Accepted' where ReviewStatusCode='GOALS_ACCEPTED'
update Review.ReviewStatus set ReviewStatusDescription ='Stage 5 - Employee - Self Assessment in progress' where ReviewStatusCode='APPRAISAL_IN_PROGRESS'
update Review.ReviewStatus set ReviewStatusDescription ='Stage 6 - Manager - Pending  Approval' where ReviewStatusCode='APPRAISAL_SUBMITTED'
update Review.ReviewStatus set ReviewStatusDescription ='Stage 6 - Employee - Need More Information' where ReviewStatusCode='NEED_TO_EDIT_APPRAISAL'
update Review.ReviewStatus set ReviewStatusDescription ='Stage 7 - Manager - Pending Approval' where ReviewStatusCode='ASSESSMENT_IN_PROGRESS'
update Review.ReviewStatus set ReviewStatusDescription ='Stage 7 - Manager Employee Discussion' where ReviewStatusCode='READY_FOR_MEETING'
update Review.ReviewStatus set ReviewStatusDescription ='Stage 8 - Completed' where ReviewStatusCode='COMPLETED'